Block Out user interface; fixes #2
RHEAGROUP/DEHP-ECOSIMPRO pull request #28
Opened 2020-10-18 07:34 UTC by nathanatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/DEHP-ECOSIMPRO/pulls) open
- [x] I have verified that I am following the DEHP-EcosimPro [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/DEHP-ECOSIMPRO/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

; fixes #2
- [x] added Views
- [x] added DEHPCommon package
- [x] Autofac

![image](https://user-images.githubusercontent.com/61700723/96361337-1fce2d80-1125-11eb-9244-9e974619694e.png)

2020-10-19 09:18 UTC, samatrhea requested changes

2020-10-19 09:18 UTC, samatrhea commented on DEHPEcosimPro/Enumerators/MappingDirection.cs
> +        /// Left means from EcosimPro to 10-25 source
the names are not clear and need docs to be explanatory, i find the left-to-right idea a bit odd. Can you make the directionality more explicit please? And, is this not something that is more for Common? All DST adaptors will have a MappingDirection where on the one side we have 10-25 and the other we have a DST.

2020-10-19 09:18 UTC, samatrhea commented on DEHPEcosimPro/Views/Rows/MappingThing.xaml.cs
> +// <copyright file="MappingRow.xaml.cs" company="RHEA System S.A.">
this does not correspond to the class name, also, can i suggest to make it `MappingThingControl` ?

2020-10-19 09:18 UTC, samatrhea commented on appveyor.yml
> +         secure: uS7/WlBplrAs/j9ab9P3SUN7GZyf4QAHZX//YpDOzXG/DZ6o1MGHdIWLHHdDYM5P
this should indeed **not** be here... please add a ticket somewhere so this is captured that work needs to be done ASAP

2020-10-19 09:39 UTC, lxatrhea approved these changes
Only one question: Should all the ThingIcon stuff be moved to DEHPCommon?

2020-10-20 07:56 UTC, samatrhea approved these changes

2020-10-20 08:05 UTC, alexatrhea requested changes
Quite a bit of refactoring needed. Please also in general place some sort of visual indicator in the main window that shows the direction of transfer.

2020-10-20 08:05 UTC, alexatrhea commented on DEHPEcosimPro/Views/DataSourcePanel.xaml
> +﻿<UserControl x:Class="DEHPEcosimPro.Views.DataSourcePanel"
not clear what this does, perhaps rename?

2020-10-20 08:05 UTC, alexatrhea commented on DEHPEcosimPro/Views/Rows/MappingThingControl.xaml
> +﻿<UserControl x:Class="DEHPEcosimPro.Views.Rows.MappingThingControl"
common perhaps as well?

2020-10-20 08:05 UTC, alexatrhea commented on DEHPEcosimPro/Views/SplashScreen.xaml
> +﻿<dx:SplashScreenWindow x:Class="DEHPEcosimPro.Views.SplashScreen"
Common?

2020-10-20 08:05 UTC, alexatrhea commented on DEHPEcosimPro/Views/StatusBarControl.xaml
> +﻿<StatusBar x:Class="DEHPEcosimPro.Views.StatusBarControl"
common?

2020-10-22 19:25 UTC, alexatrhea approved these changes

2020-10-22 20:44 UTC, merged