Connection status header and calling server methods; fixes #35
RHEAGROUP/DEHP-ECOSIMPRO pull request #39
Opened 2021-01-08 13:12 UTC by ahmedatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/DEHP-ECOSIMPRO/pulls) open
- [x] I have verified that I am following the DEHP-EcosimPro [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/DEHP-ECOSIMPRO/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
fixes #35 
- Added some server and connection status properties to the DstBrowserHeaderViewModel
- Added capability of calling the Run and Reset server methods from the DstBrowserHeaderViewModel
- Added two methods for retrieving the server start and current times in the DstController

2021-01-08 13:35 UTC, alexatrhea requested changes

2021-01-08 13:35 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/DstBrowserHeaderViewModel.cs
> +        private DateTime? currentServerTime;
Please group private fields together and public properties together. The private fields should be at the top of file, while Properties come directly after constructors. You can setup Resharper to do this for you and be taken in to account as part of the Cleanup function.

2021-01-08 15:28 UTC, alexatrhea approved these changes

2021-01-11 08:31 UTC, nathanatrhea approved these changes

2021-01-11 09:01 UTC, merged